In [2]:
import pandas as pd
import json
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

print("Pronto!")

Pronto!

In [3]:
load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")
engine = create_engine(DATABASE_URL)

print("Conexão criada com sucesso!")

Conexão criada com sucesso!

In [3]:
with open("data/raw/deputados.json", "r", encoding="utf-8") as f:
    deputados = json.load(f)

df_deputados = pd.DataFrame(deputados)[['id', 'nome', 'siglaPartido', 'siglaUf', 'idLegislatura', 'email']]


df_deputados.head()

,id,nome,siglaPartido,siglaUf,idLegislatura,email
0,204379,Acácio Favacho,MDB,AP,57,dep.acaciofavacho@camara.leg.br
1,220714,Adail Filho,MDB,AM,57,dep.adailfilho@camara.leg.br
2,221328,Adilson Barroso,PL,SP,57,dep.adilsonbarroso@camara.leg.br
3,204560,Adolfo Viana,PSDB,BA,57,dep.adolfoviana@camara.leg.br
4,204528,Adriana Ventura,NOVO,SP,57,dep.adrianaventura@camara.leg.br

In [4]:
df_deputados.to_sql('deputados', engine, if_exists='replace', index=False)

print("Deputados carregados no banco!")

Deputados carregados no banco!

In [9]:
with open("data/raw/despesas.json", "r", encoding="utf-8") as f:
    despesas = json.load(f)

df_despesas = pd.DataFrame(despesas)[['ano', 'mes', 'tipoDespesa', 'codDocumento', 'tipoDocumento', 'codTipoDocumento', 'dataDocumento', 'numDocumento', 'valorDocumento', 'nomeFornecedor', 'cnpjCpfFornecedor', 'valorLiquido', 'codLote', 'id_deputado']]


df_despesas.head()

,ano,mes,tipoDespesa,codDocumento,tipoDocumento,codTipoDocumento,dataDocumento,numDocumento,valorDocumento,nomeFornecedor,cnpjCpfFornecedor,valorLiquido,codLote,id_deputado
0,2026,5,COMBUSTÍVEIS E LUBRIFICANTES.,8097884,Nota Fiscal Eletrônica,4,2026-05-07T09:42:54,1454922,538.89,FORTE COMERCIO DERIVADOS DE PETROLEO LTDA II,07848998000209,538.89,2235045,220714
1,2026,5,COMBUSTÍVEIS E LUBRIFICANTES.,8097881,Nota Fiscal Eletrônica,4,2026-05-13T08:43:49,1461667,303.00,FORTE COMERCIO DERIVADOS DE PETROLEO LTDA II,07848998000209,303.00,2235045,220714
2,2026,5,COMBUSTÍVEIS E LUBRIFICANTES.,8100258,Nota Fiscal Eletrônica,4,2026-05-17T21:12:52,12937,200.00,MUCURIPE COMERCIO DE COMBUSTIVEIS LTDA,84110394003308,200.00,2236332,220714
3,2026,5,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,8096925,Recibos/Outros,1,2026-05-12T00:00:00,1653,6000.00,NSF TRANSPORTES ME LTDA.,19533015000143,6000.00,2234471,220714
4,2026,5,COMBUSTÍVEIS E LUBRIFICANTES.,8097890,Nota Fiscal,0,2026-05-03T00:00:00,167987,312.70,auto posto bombonato ltda,96640362000116,312.70,2235060,221328

In [10]:
df_despesas.to_sql('despesas', engine, if_exists='replace', index=False)

print("Despesas carregadas no banco!")

Despesas carregadas no banco!

In [15]:
with open("data/raw/partidos.json", "r", encoding="utf-8") as f:
    partidos = json.load(f)

df_partidos = pd.DataFrame(partidos)[['id', 'sigla', 'nome']]


df_partidos.head()

      id      sigla                              nome
0  36898     AVANTE                            Avante
1  37905  CIDADANIA                         Cidadania
2  36899        MDB  Movimento Democrático Brasileiro
3  38011     MISSÃO                    Partido Missão
4  37901       NOVO                      Partido Novo

In [16]:
df_partidos.to_sql('partidos', engine, if_exists='replace', index=False)

print("partidos carregadas no banco!")

partidos carregadas no banco!

In [25]:
with open("data/raw/proposicoes.json", "r", encoding="utf-8") as f:
    proposicoes = json.load(f)

df_proposicoes = pd.DataFrame(proposicoes)[['id', 'siglaTipo', 'codTipo', 'numero', 'ano', 'ementa', 'dataApresentacao']]


df_proposicoes.head()

,id,siglaTipo,codTipo,numero,ano,ementa,dataApresentacao
0,106701,PL,139,347,2003,"Altera a Lei nº 9.605, de 12 de fevereiro de 1...",2003-03-17T11:08
1,155019,PL,139,3055,2004,"Cria o Programa Nacional de Coleta, Armazename...",2004-03-04T15:31
2,264726,PL,139,4149,2004,"Dá nova redação ao art. 15 da Lei nº 10.826, d...",2004-09-15T16:48
3,271967,PL,139,4555,2004,Dispõe sobre a obrigatoriedade da Natureza Púb...,2004-12-02T16:46
4,318352,PL,139,6792,2006,Altera o caput e o inciso II do art. 22 da Lei...,2006-03-22T22:18

In [20]:
df_proposicoes.to_sql('proposicoes', engine, if_exists='replace', index=False)

print("Proposições carregadas no banco")

Proposições carregadas no banco

In [22]:
with open("data/raw/votacoes.json", 'r', encoding="utf-8") as f:
    votacoes = json.load(f)

df_votacoes = pd.DataFrame(votacoes)[['id', 'data', 'proposicaoObjeto', 'descricao', 'aprovacao']]

df_votacoes.head()

,id,data,proposicaoObjeto,descricao,aprovacao
0,2434055-38,2025-05-21,NaN,Aprovado o Parecer com Complementação de Voto.,1.0
1,2510145-3,2025-05-21,REQ 21/2025 CCOM,Aprovado o Requerimento para inclusão na lista...,1.0
2,2509569-3,2025-05-21,REQ 19/2025 CCOM,Aprovado o Requerimento para inclusão na lista...,1.0
3,2509169-3,2025-05-21,REQ 17/2025 CCOM,Aprovado o Requerimento para inclusão na lista...,1.0
4,2509114-3,2025-05-21,REQ 16/2025 CCOM,Aprovado o Requerimento para inclusão na lista...,1.0

In [23]:
df_votacoes.to_sql('votacoes', engine, if_exists='replace', index=False)

print('Votações carregadas no banco')

Votações carregadas no banco